__3.1.__ Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а) A  — матрица  4×2 ,  B  — матрица  4×2 ;
AB и BA не определены, т.к. количество строк матрицы A не совпадает с количеством столбцов матрицы B и наоборот.

б) A  — матрица  2×5 ,  B  — матрица  5×3 ;
AB определено, размерность получившейся матрицы 2×3.
BA не определено, т.к. количество строк матрицы B не совпадает с количеством столбцов матрицы A.

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;
Оба произведения определены, размерности:
    АВ: 8х8
    ВА: 3х3

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .
Оба произведения определены, размерности обоих 4х4

__3.2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.
$$

$$ A\cdot B =
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot (-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot (-1) + 0\cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.
$$

$$ B\cdot A =
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = 
\begin{pmatrix}
4\cdot 1 + (-1)\cdot 3 & 4\cdot (-2) + (-1)\cdot 0\\ 
0\cdot 1 + 5\cdot 3 & 0\cdot (-2) + 5\cdot 0
\end{pmatrix} = 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.
$$

In [76]:
import numpy as np

In [77]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$
3A-2B+4C = 
3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} =
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} =
\begin{pmatrix}
11 & 15\\ 
9 & -16
\end{pmatrix}
$$

__3.4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$.

$$A\cdot A^{T}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}.$$

$$A^{T}\cdot A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$$

In [78]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{a}\n')
print(f'Транспонированная матрица:\n{a.T}\n')
print(f'A*(A^T):\n{a @ a.T}\n')
print(f'(A^T)*A:\n{a.T @ a}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]

A*(A^T):
[[17 18 11]
 [18 29  4]
 [11  4 13]]

(A^T)*A:
[[45  0]
 [ 0 14]]


__3.5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [79]:
A = [[1, 0], [2, 1], [10, 5]]
B = [[2, 0, 0], [0, 0, 1]]

def matrix_prod(A,B):
    
    if len(A)==len(B[0]):
        result = []
        for i in range(len(A)):
            row = []
            for j in range(len(A)):
                count = 0
                for k in range(len(B)):
                    count += A[i][k]*B[k][j]
                row.append(count)
            result.append(row)
        print(f'{A = }\n{B = }')
        print(f'Результат произведения матриц {result}')
    else:
        print('Неправильные данные')
        
matrix_prod(A, B)


A = [[1, 0], [2, 1], [10, 5]]
B = [[2, 0, 0], [0, 0, 1]]
Результат произведения матриц [[2, 0, 0], [4, 0, 1], [20, 0, 5]]


__4.1.__ Вычислить определитель:

   a)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sinx \cdot sinx - cosx \cdot (-cosx) = 1.$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 
4\cdot5\cdot9 = 180
$$

In [80]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [83]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__4.2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
   
   $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$

    
   б) $det(A^{T})$;
   
   Определитель транспонированной матрицы равен определителю исходной матрицы.
   Следовательно $det(A^{T}) = 4$
    
   в) $det(2A)$.
   
   Пусть размер матрицы n строк и n столбцов. Если все элементы матрицы умножить на число 2, то это равносильно каждой строке, умноженной на 2. 
   
   Если одну строку умножить на число, то определитель умножится на это число. Следовательно, определитель умножится на $2^{n}$.
   
   $det(2A) = 2^{n} \cdot det(A) = 2^{n} \cdot 2^{2} = 2^{2 + n}$

__4.3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

$ \begin{pmatrix}4 & -14 & 6\end{pmatrix} = -2 \cdot \begin{pmatrix}-2 & 7 & -3\end{pmatrix}$

Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

__4.4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

Вычтем из первой строки вторую, и поменяем их местами:
$\begin{pmatrix}
1 & 1 & 1\\
0 & 1 & 2
\end{pmatrix};$

Таким образом, ранг матрицы равен  2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}.$

Вычтем из второй строки первую, и переместим 1 строку наверх:
$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 1\\  
0 & 0 & 0 & 1
\end{pmatrix}.$

Таким образом, ранг матрицы равен  3.

In [113]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(a)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы:
2


In [114]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(a)}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы:
3
