## Задание 6

__6.1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


__Решение__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из второй строки первую, умноженную на 2, и из третьей первую:
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

В данном случае система имеет _бесконечное количество решений._

Оставшаяся матрица соответствует системе

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~-2x_{3}+3x_{4}=4,
\end{cases}$$

Рассмотрим в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $с$, получим:

$$x_{4}=c,$$
$$-2x_{3}+3c=4\; \Leftrightarrow \; x_{3}=-2+1,5c,$$
$$-x_{2}-2+1,5c+5c=-2 \; \Leftrightarrow \; x_{2}=6,5c,$$
$$x_{1} + 6,5c + 2 - 1,5c - 2c = 0 \; \Leftrightarrow \; x_{1}=-3c-2.$$

Таковым будет _общее решение системы_. Подставляя произвольные числа вместо $c$, мы получим _частное решение_. Например, при $c=0$:

$$x_{1}=-2,$$
$$x_{2}=0,$$
$$x_{3}=-2.$$
$$x_{4}=0.$$

Параметр $c$ может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

Подставив общее решение в исходную систему, также получим тождества:

$$\begin{cases}
-3c-2+6,5c+2-1,5c-2c = 0, \\
-6c-4+6,5c+2-1,5c+c = -2, \\
-3c-2+6,5c+6-4,5c+c = 4.
\end{cases}$$

__6.2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

In [1]:
import numpy as np

In [2]:
def solutions(matr, exp_matr):
    rank_matr = np.linalg.matrix_rank(matr)
    rank_exp_matr = np.linalg.matrix_rank(exp_matr)
    n = len(matr[0])

    print(f'Матрица:\n{matr}')
    print(f'Расширенная матрица:\n{exp_matr}\n')
    print(f'Ранг матрицы: {rank_matr}')
    print(f'Ранг расширенной матрицы: {rank_exp_matr}')
    print(f'Количество неизвестных: {n}\n')
    
    if rank_matr == rank_exp_matr == n:
        print('Данная система определена, т. е. имеет единственное решение\n')
    elif (rank_matr == rank_exp_matr) & (rank_matr < n):
        print('Данная система имеет бесконечное количество решений\n')
    else:
        print('Данная система несовместна\n')
        

a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
ta = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
    
b = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
tb = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

c = np.array([[1, 2, 5], [3, 1, -8]])
tc = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

print('а)')
solutions(a, ta)
print('б)')
solutions(b, tb)
print('в)')
solutions(c, tc)

а)
Матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Расширенная матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

Ранг матрицы: 3
Ранг расширенной матрицы: 3
Количество неизвестных: 3

Данная система определена, т. е. имеет единственное решение

б)
Матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Расширенная матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

Ранг матрицы: 1
Ранг расширенной матрицы: 2
Количество неизвестных: 3

Данная система несовместна

в)
Матрица:
[[ 1  2  5]
 [ 3  1 -8]]
Расширенная матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

Ранг матрицы: 2
Ранг расширенной матрицы: 2
Количество неизвестных: 3

Данная система имеет бесконечное количество решений



__6.3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [3]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
ta = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

solutions(a, ta)

Матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Расширенная матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

Ранг матрицы: 4
Ранг расширенной матрицы: 4
Количество неизвестных: 4

Данная система определена, т. е. имеет единственное решение



__6.4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__

Приведем расширенную матрицу к треугольной форме. Для этого из второй строки вычтем первую, умноженную на $4$, а из третьей первую, умноженную на $7$:
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}

Далее из третьей строки вычтем вторую умноженную на $2$Ж
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a - 2b + 8a
\end{matrix}
\end{pmatrix}

Для того, чтобы система была несовместной необходимо, чтобы ранг расширенной матрицы был больше ранга самой матрицы (2).
Следовательно, $c + a - 2b \ne 0$

$a \ne 2b - c$, например, вектор
$(1,4,7)$

## Задание 7

__7.1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}
=1 \cdot (-4)-3\cdot (-2)=2\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=1 \cdot (-4)-7\cdot (-2)=10,$$


$$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=1 \cdot 7-3\cdot 1=4,$$


Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [24]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
a_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_a = np.linalg.det(a)
det_a_1 = np.linalg.det(a_1)
det_a_2 = np.linalg.det(a_2)
det_a_3 = np.linalg.det(a_3)
print(f'Определитель a: {det_a:.0f}')
print(f'Определитель a_1: {det_a_1:.0f}')
print(f'Определитель a_2: {det_a_2:.0f}')
print(f'Определитель a_3: {det_a_3:.0f}')
x_1 = det_a_1 / det_a
x_2 = det_a_2 / det_a
x_3 = det_a_3 / det_a
print(f'{x_1 = :.0f}')
print(f'{x_2 = :.0f}')
print(f'{x_3 = :.0f}')

Определитель a: 43
Определитель a_1: 86
Определитель a_2: -43
Определитель a_3: 43
x_1 = 2
x_2 = -1
x_3 = 1


__7.2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

__Решение__

Домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

Домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. После вычтем из четвертой строки первую, домноженную на $4$ и запишем $l_{41}=4$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0  \\ 
2 & 1 & 0 & 0  \\ 
3 & l_{32} & 1 & 0  \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$

Домножим вторую строку на $5$ и вычтем ее из третьего уравнения. При этом запишем в матрицу $L$ на место элемента $l_{32}$ значение $5$. Затем нам нужно вычесть из четвертого уравнения второе, домноженное на $6$. Значит, в матрицу $L$ запишем $l_{42}=6$.

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 6\\
0 & 0 & 21 & 17
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0  \\ 
2 & 1 & 0 & 0  \\ 
3 & 5 & 1 & 0  \\
4 & 6 & l_{43} & 1
\end{pmatrix}.$$

Далее умножим третью строку на $7$ и вычтем ее из четвертой. При этом в матрицу $L$ на место $l_{43}$ запишем $7$.

В итоге получим

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 6\\
0 & 0 & 0 & -25
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}.$$

__7.3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__Решение__

Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.$$

Домножим первую строку на $11/2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $5,5$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $9/2$. Значит, в матрицу $L$ запишем $l_{31}=4,5$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1,5 & -11,5 \\ 
0 & 3,5 & -9,5
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
5,5 & 1 & 0 \\ 
4,5 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $7/3$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $7/3$.

В итоге получим

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1,5 & -11,5 \\ 
0 & 0 & 52/3
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
5,5 & 1 & 0 \\ 
4,5 & 7/3 & 1
\end{pmatrix}.$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
5,5y_{1}+y_{2}=-6, \\
4,5y_{1}+7y_{2}/3+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-11,5,$$
$$y_{3}=52/3.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
1,5x_{2}-11,5x_{3}=-11,5, \\
52/3x_{3}=52/3.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

$$\begin{cases}
2\cdot (-1)+0+3\cdot 1=1 \\
11\cdot (-1)+7\cdot 0+5\cdot 1=-6 \\
9\cdot (-1)+8\cdot 0+4\cdot 1=-5
\end{cases}$$

Таким образом, найденное решение верно.

__7.4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$l_{11}=\sqrt{a_{11}}=9,$

$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$

$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$

$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$

$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5} \left ( -15 - (-5)\cdot 5 \right )=2,$

$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-33,$$

$$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}+(-5)x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=-5,$$

$$x_{1}=6.$$

Осуществим проверку, подставив полученные значения в исходную систему:

$$\begin{cases}
81\cdot 6-45\cdot (-5)+45\cdot (-4)=531 \\
-45\cdot 6+50\cdot (-5)-15\cdot (-4)=-460 \\
45\cdot 6-15\cdot (-5)+38\cdot (-4)=193
\end{cases}$$

Таким образом, найденное решение верно.

In [31]:
from scipy.linalg import solve_triangular
A = np.matrix([[81, -45, 45],[-45, 50, -15],[45, -15, 38]])
B = np.array  ([531, -460, 193])
 
#Разложение Холецкого
L = np.linalg.cholesky(A)
Y = solve_triangular(L, B, lower = True)
X = solve_triangular(L, Y, lower = True, trans = 1)
print(X)

[ 6. -5. -4.]


__7.5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.


К большому сожалению - не успел:(